Upgrade to Node 14.x
Node 8 is no longer supported, and 14.x appears to be the most recent
version of Node supported by puppeteer; at least, the Docker build
fails for any newer versions of Node with:
> [13/18] RUN npm install puppeteer:
------
Dockerfile:149
--------------------
 147 |     ###
 148 |
 149 | >>> RUN npm install puppeteer
 150 |
 151 |     ###
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install puppeteer" did
not complete successfully: exit code: 1

Upgrading to Node 14 also necessitates installing sudo and upgrading
the Ubuntu base Docker image to 20.04.  The reasons these two changes
are now necessary are explained here:
https://github.com/nodesource/distributions

(This URL is where https://deb.nodesource.com redirects to.)